### ISSUE TITLE
Määriteltävä koodisto RakentamisenSuunnitelmanLaji

### ISSUE THREAD

**Issue by ilkkarinne** [ilkkarinne/rakennuskohteet#61]
UML-mallissa on CodeList ```RakentamisenSuunnitelmanLaji```, joka laajentaa tyhjää koodistoluokkaa ```AbstraktiAsiankirjanLaji```, jolta puuttuu Y-alustan koodisto. Koodisto käytössä ```Liiteasiakirja```-luokan objekteissa, kuten ```Erityissuunnitelma.tiedosto```

**Comment by teempek** [comment]
Mitä tällä koodistolla tarkoitetaan?

**Comment by ilkkarinne** [comment]
Tehty yhdistetty koodisto ```LuvanvaraisenRakentamisenAsiakirjanLaji```, jolla ei toistaiseksi ole Y-laustan koodistoa, ks. #60 ja #59
